services:
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: azurite
    command: >
      azurite
      --blobHost 0.0.0.0
      --queueHost 0.0.0.0
      --tableHost 0.0.0.0
      --location /data
      --debug /data/debug.log
    ports:
      - "10000:10000"  # Blob
      - "10001:10001"  # Queue
      - "10002:10002"  # Table
    volumes:
      - azurite_data:/data

  app:
    build: .
    container_name: pocpdf-app
    depends_on:
      - azurite
    environment:
      SERVER_PORT: 8080
      SOFFICE_PATH: /usr/bin/soffice
      AZURE_STORAGE_CONNECTION_STRING: >-
        DefaultEndpointsProtocol=http;
        AccountName=devstoreaccount1;
        AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;
        BlobEndpoint=http://azurite:10000/devstoreaccount1;
        QueueEndpoint=http://azurite:10001/devstoreaccount1;
        TableEndpoint=http://azurite:10002/devstoreaccount1;
    ports:
      - "8080:8080"
    working_dir: /app
    volumes:
      - ./templates:/app/templates
      - ./out:/app/out

volumes:
  azurite_data:
